@extends('layouts.admin')
@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
{{Form::open(array('url'=>'/message'))}}
<div class="row">
    <div class="col-md-12">

        
        <div class="row">
            <div class="form-group col-md-6 ">
                <p class="help-block">A reader friendly name to help us identify what this message is.</p>
                {{Form::text('name', null, array('class'=>'form-control', 'placeholder'=>'Name'))}}
            </div>

            <div class="form-group  col-md-6 ">
                <p class="help-block">Command Prompt.  What does  user type that prompts message? </p>
                {{Form::text('command', null, array('class'=>'form-control', 'placeholder'=>'Command'))}}
            </div>
        </div>


        <div class="form-group">
            <p class="help-block">The message sent to the user.</p>
            {{Form::text('content', null, array('class'=>'form-control', 'placeholder'=>'Message'))}}
        </div>
        <div class="form-group">
            <p class="help-block">Is this a response to user input?  This helps block system texts from being generated by incoming user texts.</p>
            {{Form::select('response',  array('0'=>'System Generated Message', '1'=>'System Generated Message Or Inbound Response'),0, array('class'=>'form-control'))}}
        </div>
        <div class="form-group text-left">
            <p class="help-block">Internal notes about this message.</p>
            {{Form::textarea('notes', null, array('class'=>'form-control', 'placeholder'=>'Notes'))}}
        </div>

        {{Form::submit()}}

    </div>
</div>







{{Form::close()}}

    @endsection