@extends('layouts.admin')
@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {{Form::open(array('url'=>'/message/'.$m->id, 'method'=>'patch'))}}
    <div class="row">
        <div class="col-xs-12 message">
            <div class="form-group">
                {{Form::text('name', $m->name, array('class'=>'form-control', 'placeholder'=>'Name'))}}
                <p class="help-block">A reader friendly name to help us identify what this message is.</p>
            </div>
            <div class="form-group">
                {{Form::text('command', $m->command, array('class'=>'form-control', 'placeholder'=>'Command'))}}
                <p class="help-block">What command prompts this message.  What does the user types that prompts this message? </p>

            </div>
            <div class="form-group">
                {{Form::text('content', $m->content, array('class'=>'form-control', 'placeholder'=>'Message'))}}
                <p class="help-block">The message sent to the user.</p>
            </div>
            <div class="form-group">
                {{Form::select('response',  array('0'=>'System Generated Message', '1'=>'System Generated Message Or Inbound Response'),$m->response, array('class'=>'form-control'))}}
                <p class="help-block">Is this a response to user input?  This helps block system texts from being generated by incoming user texts.</p>
            </div>
            <div class="form-group text-left">
                {{Form::textarea('notes', $m->notes, array('class'=>'form-control', 'placeholder'=>'Notes'))}}
                <p class="help-block">Internal notes about this message.</p>
            </div>
            {{Form::submit()}}
        </div>
    </div>







    {{Form::close()}}

@endsection